### ISSUE TITLE
help...

### ISSUE THREAD

**Issue by asdfgasdfgyuash** [Mantelyys/browsers-data-grabber#11]
![image](https://user-images.githubusercontent.com/85171325/171106398-ab402b1c-0cdb-43c5-b968-afae28b2dda2.png)

**Comment by Mantelyys** [comment]
What's your discord?

**Comment by asdfgasdfgyuash** [comment]
opera gx, microsoft edge, chrome password, cookie not steal.

**Comment by asdfgasdfgyuash** [comment]
chrome, opera gx, opera stable, firefox, microsoft edge are installed.

**Comment by Mantelyys** [comment]
SEND ME YOUR DISCORD

**Comment by asdfgasdfgyuash** [comment]
> SEND ME YOUR DISCORD

Wapper#0384
