### ISSUE TITLE
Tried and Here is Results

### ISSUE THREAD

**Issue by PandoricGalaxy** [Mantelyys/browsers-data-grabber#3]
I tried it on a rdp and here are the browsers i tried it on:

**- Brave
- Opera
- OperaGX
- Chrome
- Edge**

Here is what i got:

![image](https://user-images.githubusercontent.com/86944806/169777546-387ac05b-fd59-46b2-b1c9-aed26f82a93e.png)

It didn't steal OperaGX so please fix OperaGX

**Comment by Mantelyys** [comment]
Will look into it.

**Comment by PandoricGalaxy** [comment]
> Will look into it.

thanks!

**Comment by Mantelyys** [comment]
I hope it is fixed now

**Comment by PandoricGalaxy** [comment]
It did send a file but...
![image](https://user-images.githubusercontent.com/86944806/169810621-81f18b41-18d5-47f3-bf69-ffe1456a78e6.png)
 The login data is empty..
![image](https://user-images.githubusercontent.com/86944806/169810859-5d697a0f-ad3c-4672-933f-88cf397d53aa.png)
although i have passwords saved..
![image](https://user-images.githubusercontent.com/86944806/169810750-c814becd-dee8-44eb-97c4-6cae0e164c92.png)
the cookies work

**Comment by Mantelyys** [comment]
Probably fixed

**Comment by PandoricGalaxy** [comment]
Works now 👍
