### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by asdfgasdfgyuash** [Mantelyys/browsers-data-grabber#8]
![image](https://user-images.githubusercontent.com/85171325/170515129-eed00733-e855-4af6-a51e-2595ff9d2bbb.png)

**Comment by asdfgasdfgyuash** [comment]
![image](https://user-images.githubusercontent.com/85171325/170517570-6944fa56-03eb-4243-86a0-a2d29d4ff14d.png)

**Comment by asdfgasdfgyuash** [comment]
.

**Comment by PandoricGalaxy** [comment]
Idk if its actually a bug or not but if it is a bug then ive fixed it.
Ill make a pull request with the code i stole from rdimo and mantelyys and combined before mantelyys added token grabber

**Comment by Mantelyys** [comment]
Won't show an error no more.
